on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install npm v8
        run: npm i -g npm@8
      - name: install
        run: npm install
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: build
        run: make build
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
